Repository opendatahub-io/modelmesh, pull requests merged in 2025-09, with the labels that each got.

#101 [RHOAIENG-32568] Model serving builds for ODH community 2.34
  .tekton/odh-modelmesh-push.yaml
Labels: approved

#105 Add Konflux ODH tag bump automation to our existing release workflow.
  .github/workflows/create-release-tag.yml
Labels: approved, lgtm

#106 Sync/release 0.12.0 rc0 stable 2.x
  .github/workflows/create-release-tag.yml
  .tekton/odh-modelmesh-push.yaml
Labels: approved, lgtm, tide/merge-method-merge
